pool:
  vmImage: 'windows-latest'

steps:
- task: MavenAuthenticate@0
  inputs:
    mavenFeed: '$(MavenFeed)'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-X'
    goals: 'clean install'
