trigger:
  branches:
    include:
      - main  # Ce pipeline se déclenchera lorsque vous pousserez des modifications sur la branche 'main'

pool:
  name: 'Default'  # Le nom du pool local où vous avez configuré votre agent auto-hébergé
  

steps:
# Étape 1: Récupérer le code source
- task: Checkout@1
  inputs:
    repository: self  # Utilise le dépôt actuel du pipeline
    fetchDepth: 1  # Limite la profondeur du clone à 1 (récupère seulement le dernier commit)
